public class ProblemRNA
{
    public static void main() {
        // replace this string with the one from Project Rosalind
        final String inputDNA = "GCAAGGATGGCATCGGCCATAGGCTAAGACCTGCGCGGATAGAAAGGGCGGTTCATCTCTAAATAGCCAGCTTTCAACGTCATTGACGGACATCCAGGTCATCGTACATGTTGGTACAATCGCGGGTGAACGAGCCAGCACTGAATGTACCTCTACCTACTGGGTTTTGGATAATAAGGTAACCATGCGGCCCGAGATGACAATCACCGGTTGCAGAGAATGGGGAAGTTGGGGTACCCCCCCTGAGGTTGGCCTCTCTGTGCCCGCCCACCTTCACGCATTTGTGGAACCAAACCACACCAATGTAACTGGATCCAGAACCGAGTCATTTGTCCGGTTAATAATTCCATCACCGCAACCCGTTTCAGACGCGAGCAACCGCTAGAATTGATTCAACCAGATCCGAGGAATTCACCGCCCATCCTTTCTGCTAGGCAGCCTAGATGTTCCCCCCTAGCTAGTTGCTCTTTTCTTTAGCCTGGATGCGATCCAGGACCAAAAATTAGAGTTAATACCGTAAAGTAACGTTTGAATATGGTACCGTAACCAGAGGAACGACCGGATTTTGGAACACGACTTGTAAGTGAGGAATAGGATGTGGGTTGCGGTCAACTGGGAGAACTTCCAGTGCACGGATGGAGCGATGGAATGAAAGGGGGATGTACCTGTCGAGTTACTCAGACCGGCTTGCATTCGGTGATGGCCAACTGCAAAACACTGTACTTGGCCCGTATTCCCTACGGTTGAGGGGTCCTTGGGAAGTGTCCGGTGCGTGTCCAAGGCTGTTACGTGAATTCACACTAGTTCCAAAGCAGCGCATATGGTCATAGGCCGTAGCCTGAAGTGTGACACGGGAACACGCGGCTGGTAGACCGTCCATTTGAGCGCATACACGAATCCTTTAGGTCAAGCGAATACTCGTC";
        final String output = transcribeDNAtoRNA(inputDNA);
        // you can copy and paste from the terminal window into 
        //   Project Rosalind to check your answer
        System.out.println(output);
    }
    private static String transcribeDNAtoRNA(String dnaString) {
        String result = "";
        for(int i = 0; i< dnaString.length(); i++) {
            char c = dnaString.charAt(i);
            
            if (c == 'T') {
                result += 'U';
            } else {
                result += c;
            }
            }
            return result;
        }
    }
    
